img_path: /data/kimsj/project/wku_rcft/image/tiff/
out_path: /data/kimsj/project/wku_rcft/result/tiff/
black_preprocessing: True
rcft:
    # - copy
    - immediate
    # - delay
adaptive_threshold:
    block_size: 17
    c: 5
remove_background:
    copy:
        left: 80
        right: -80
        up: 10
        down: -208
    immediate:
        left: 80
        right: -80
        up: 480
        down: -508
    delay:
        left: 80
        right: -80
        up: 480
        down: -508
